In [33]:
import pandas as pd

# Load from a CSV file
df = pd.read_csv("../data/inference.csv")
df.head()

,index,store_ID,day_of_week,date,nb_customers_on_day,open,promotion,state_holiday,school_holiday
0,272371,415,7,01/03/2015,0,0,0,0,0
1,558468,27,7,29/12/2013,0,0,0,0,0
2,76950,404,3,19/03/2014,657,1,1,0,0
3,77556,683,2,29/01/2013,862,1,0,0,0
4,456344,920,3,19/03/2014,591,1,1,0,0

In [34]:
import Data_preparation as dp
COLS_TO_DROP = ["index", "date", "store_ID"]
df.drop(columns=COLS_TO_DROP, inplace=True)

In [35]:
df = dp.encode_state_holiday(df)
df

,day_of_week,nb_customers_on_day,open,promotion,school_holiday,state_hol_0,state_hol_1,state_hol_2,state_hol_3
0,7,0,0,0,0,1,0,0,0
1,7,0,0,0,0,1,0,0,0
2,3,657,1,1,0,1,0,0,0
3,2,862,1,0,0,1,0,0,0
4,3,591,1,1,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...
71200,7,0,0,0,0,1,0,0,0
71201,7,0,0,0,0,1,0,0,0
71202,3,648,1,0,0,1,0,0,0
71203,2,626,1,1,0,1,0,0,0
71204,4,828,1,1,0,1,0,0,0

In [36]:
df_scales , scaler = dp.scale_data(df)
df_scaled = pd.DataFrame(df_scales, columns=df.columns)
df_scaled.head(5)

   day_of_week  nb_customers_on_day      open  promotion  school_holiday  \
0     1.501395            -1.357070 -2.210138  -0.782440        -0.46723
1     1.501395            -1.357070 -2.210138  -0.782440        -0.46723
2    -0.501103             0.050536  0.452460   1.278053        -0.46723
3    -1.001727             0.489743  0.452460  -0.782440        -0.46723
4    -0.501103            -0.090867  0.452460   1.278053        -0.46723

   state_hol_0  state_hol_1  state_hol_2  state_hol_3
0     0.176661    -0.141876    -0.081949    -0.062266
1     0.176661    -0.141876    -0.081949    -0.062266
2     0.176661    -0.141876    -0.081949    -0.062266
3     0.176661    -0.141876    -0.081949    -0.062266
4     0.176661    -0.141876    -0.081949    -0.062266

,day_of_week,nb_customers_on_day,open,promotion,school_holiday,state_hol_0,state_hol_1,state_hol_2,state_hol_3
0,1.501395,-1.357070,-2.210138,-0.782440,-0.46723,0.176661,-0.141876,-0.081949,-0.062266
1,1.501395,-1.357070,-2.210138,-0.782440,-0.46723,0.176661,-0.141876,-0.081949,-0.062266
2,-0.501103,0.050536,0.452460,1.278053,-0.46723,0.176661,-0.141876,-0.081949,-0.062266
3,-1.001727,0.489743,0.452460,-0.782440,-0.46723,0.176661,-0.141876,-0.081949,-0.062266
4,-0.501103,-0.090867,0.452460,1.278053,-0.46723,0.176661,-0.141876,-0.081949,-0.062266

In [37]:
df_scaled.shape

(71205, 9)

In [38]:
import pickle
with open("../models/decision_tree.pkl", "rb") as f:
    final_tree = pickle.load(f)

df["sales"] = final_tree.predict(df_scaled)
df.to_csv("../data/group6.csv", index=False)

c:\Users\PCACER\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2823: UserWarning: X has feature names, but DecisionTreeRegressor was fitted without feature names
  warnings.warn(

In [39]:
df["sales"].describe()

count    71205.000000
mean      5769.972469
std       3612.895605
min          0.000000
25%       4090.126074
50%       5930.218889
75%       7811.268159
max      35283.000000
Name: sales, dtype: float64